  Question-1

In [ ]:
import numpy as np
# q-1
empty_array=np.empty((2,2))
print("q-1:",empty_array)
# q-2
one_array=np.ones((4,2))
print("q-2:",one_array)
# q-3
filled_array=np.full((3,3),8)
print("q-3:",filled_array)
# q-4
zeros_like_array=np.zeros_like(filled_array)
print("q-4:",zeros_like_array)
# q-5
ones_like_array=np.ones_like(filled_array)
print("q-5:",ones_like_array)
# q-6
new_list=[1,2,3,4]
new_list_array=np.array(new_list)
print("q-6:",new_list_array)


q-1: [[4.79833009e-310 0.00000000e+000]
 [6.65535601e-310 6.65535607e-310]]
q-2: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
q-3: [[8 8 8]
 [8 8 8]
 [8 8 8]]
q-4: [[0 0 0]
 [0 0 0]
 [0 0 0]]
q-5: [[1 1 1]
 [1 1 1]
 [1 1 1]]
q-6: [1 2 3 4]


Question-2


In [ ]:
import numpy as np
# q-1
array=np.arange(10,50)
print("q-1:",array)
# q-2
array2=np.arange(9).reshape(3,3)
print ("q-2:",array2)
# q-3
array3=np.eye(3,3)
print("q-3:",array3)
# q-4
array4=np.random.random(30)
mean_value=array4.mean()
print("q-4:",array4)
# q-5
array5=np.random.rand(10,10)
print("q-5:",array5)
max_value=np.max(array5)
min_value=np.min(array5)
print(max_value)
print(min_value)
# q-6
array6=np.zeros(10)
array6[5]=1
print("q-6:",array6)
# q-7
array7=[1,2,0,0,4]
reverse_array=np.flip(array7)
print("q-7:",reverse_array)
# q-8
array8=np.zeros((4,4))
twod_array=np.pad(array8,pad_width=1,mode='constant',constant_values=1)
print("q-8:",twod_array)
# q-9
array9=np.zeros((8,8))
array9[1::2,::2]=1
array9[::2,1::2]=1
print ("q-9:",array9)


q-1: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
q-2: [[0 1 2]
 [3 4 5]
 [6 7 8]]
q-3: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
q-4: [0.26076976 0.8138757  0.02822659 0.11295037 0.76217898 0.16495008
 0.77312776 0.11783311 0.0905227  0.68687858 0.46864674 0.82662385
 0.90128054 0.037077   0.36230459 0.75289481 0.23967864 0.1577901
 0.84470494 0.36340344 0.11514661 0.8014334  0.14869551 0.17501325
 0.47434184 0.59256167 0.96487034 0.09627762 0.73870839 0.18748422]
q-5: [[0.43954598 0.94415731 0.31854539 0.77590203 0.33873199 0.10299405
  0.6433218  0.92363769 0.1383871  0.05022113]
 [0.2601308  0.23904679 0.51281238 0.52150299 0.74648118 0.17175109
  0.01498379 0.06405245 0.31084328 0.15722909]
 [0.94907155 0.62807277 0.86029004 0.40221805 0.98813012 0.116473
  0.70751155 0.44197384 0.26324868 0.15461078]
 [0.18369284 0.14418641 0.02576845 0.66816623 0.94475572 0.8623128
  0.42626982 0.03409026 0.09647941 0.72286

Question-3


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
# q-1
add_array=np.add(x,y)
print("q-1:",add_array)
# q-2
sub_array=np.subtract(x,y)
print("q-2:",sub_array)
# q-3
multiply_array=np.multiply(x,y)
print("q-3:",multiply_array)
# q-4
square_array=np.square(x,y)
print("q-4:", square_array)
# q-5
dot_array1=np.dot(v,w)
dot_array2=np.dot(x,v)
dot_array3=np.dot(x,y)
print("q-5:", dot_array1,dot_array2,dot_array3)
# q-6
concatenate_array=np.concatenate((x,y),axis=0)
print("q-6:",concatenate_array)
# q-7
concatenate2=np.concatenate((x,y),axis=1)
print("q-7:",concatenate2)
# cause dimension does not match


q-1: [[ 6  8]
 [10 13]]
q-2: [[-4 -4]
 [-4 -3]]
q-3: [[ 5 12]
 [21 40]]
q-4: [[ 1  4]
 [ 9 25]]
q-5: 219 [29 77] [[ 19  54]
 [ 48 137]]
q-6: [[ 1  2]
 [ 3  5]
 [ 1  4]
 [ 9 25]]
q-7: [[ 1  2  1  4]
 [ 3  5  9 25]]


Question 4


In [5]:
import numpy as np

# Part 1: Prove A * A^-1 = I
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)
result = np.dot(A_inv, A)
result = np.round(result, decimals=10)
I = np.eye(2, 2)
if np.allclose(result, I):
    print("A * A^-1 = I: Equal")
else:
    print("A * A^-1 = I: Not equal")

# Part 2: Prove AB ≠ BA
res1 = np.matmul(A, B)
res2 = np.matmul(B, A)
if np.allclose(res1, res2):
    print("AB = BA: Equal")
else:
    print("AB ≠ BA: Not equal")

# Part 3: Prove (AB)^T = B^T * A^T
transpAB = np.transpose(res1)
transpA = np.transpose(A)
transpB = np.transpose(B)
res2 = np.matmul(transpB, transpA)

if np.allclose(transpAB, res2):
    print("AB^T = B^T A^T: Equal")
else:
    print("AB^T = B^T A^T: Not equal")

# Part 4: Solve the system of linear equations using the inverse method

A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_matrix = np.array([-1, -3, 9])
A_inv = np.linalg.inv(A_matrix)
X = np.dot(A_inv, B_matrix)
print("The solution is: ", X)


A * A^-1 = I: Equal
AB ≠ BA: Not equal
AB^T = B^T A^T: Equal
The solution is:  [ 2.  1. -2.]
